### ISSUE TITLE
Display cookie information

### ISSUE THREAD

**Issue by ArchBlood** [humhub-contrib/legal#13]
Would be great if we could list in better detail about the used cookies, at the moment it just shows a message model telling the user that cookies are used without giving much detail into what cookies are used and forcing the user to accept all cookies off the bat, should show a detailed message and allow the user to accept all or only necessary cookies

**Comment by ArchBlood** [comment]
Only way that I could think of doing this is applying tab boxes within the cookies view file that explains in more detail about the cookies :thinking:

**Comment by buddh4** [comment]
I usually see such detailed cookie settings only on pages with heavy usage of advertisement services and mainly targeted for public access as news pages etc. I haven't seen such cookie settings on other social networks such as facebook or twitter. Also this would need to be implemented on module level (or at least an interface), since a module has to make sure to disable certain features if the user did not aggree to a certain cookie.
